WOOPER_TOP = ..


include $(WOOPER_TOP)/GNUmakesettings.inc


# Helper modules (ex: from Myriad like basic_utils.beam, or directly from WOOPER
# like wooper_class_manager.beam, etc.) are not listed here as dependencies,
# their possible lacking will be detected at runtime.
